app = "unavatar"
kill_signal = "SIGTERM"
kill_timeout = 5

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[http_service.concurrency]
  type = "requests"
  soft_limit = 5
  hard_limit = 10

[[http_service.checks]]
  grace_period = "3s"
  interval = "30s"
  method = "GET"
  timeout = "1s"
  path = "/ping"
